### ISSUE TITLE
Hasil Pemeriksaan Controller: Setujui dan Tolak

### ISSUE THREAD

**Issue by clauddian9** [Argonaut-B04/SIRIO#43]

**Comment by clauddian9** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Controller Hasil Pemeriksaan: Get All by Pelaksana](https://trello.com/c/4HXiHRsf/1-controller-hasil-pemeriksaan-get-all-by-pelaksana)

**Comment by Nael-Nathanael** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Hasil Pemeriksaan Controller: Setujui dan Tolak](https://trello.com/c/atgPSUJ7/23-hasil-pemeriksaan-controller-setujui-dan-tolak)

**Comment by Nael-Nathanael** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Hasil Pemeriksaan Controller: Setujui dan Tolak](https://trello.com/c/atgPSUJ7/23-hasil-pemeriksaan-controller-setujui-dan-tolak)
