### ISSUE TITLE
Employee Controller: Nonaktif

### ISSUE THREAD

**Issue by clauddian9** [Argonaut-B04/SIRIO#45]

**Comment by Nael-Nathanael** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Employee Controller: Nonaktif](https://trello.com/c/aP2LhGjW/24-employee-controller-nonaktif)

**Comment by Nael-Nathanael** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Employee Controller: Tambah, Ubah, Hapus, dan Baca](https://trello.com/c/zbbcB4JY/25-employee-controller-tambah-ubah-hapus-dan-baca)
