### ISSUE TITLE
Rekomendasi Controller: Get All by Kantor Cabang

### ISSUE THREAD

**Issue by Nael-Nathanael** [Argonaut-B04/SIRIO#47]
Mempermudah query rekomendasi untuk suatu kantor cabang tertentu.

**Comment by clauddian9** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Controller Rekomendasi: Get All by Kantor Cabang](https://trello.com/c/qhv7vvNo/20-controller-rekomendasi-get-all-by-kantor-cabang)
