### ISSUE TITLE
Bukti Pelaksanaan Controller: Setujui dan Tolak

### ISSUE THREAD

**Issue by anastasiagreta** [Argonaut-B04/SIRIO#64]

**Comment by clauddian9** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Controller Bukti Pelaksanaan: Setujui dan Tolak](https://trello.com/c/GWCIBALM/22-controller-bukti-pelaksanaan-setujui-dan-tolak)

**Comment by clauddian9** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Controller Bukti Pelaksanaan: Setujui dan Tolak](https://trello.com/c/GWCIBALM/22-controller-bukti-pelaksanaan-setujui-dan-tolak)
